### ISSUE TITLE
Copyrighted code

### ISSUE THREAD

**Issue by Fireflies** [RWCraft/EarthGames_Debug#1]
KodekPL is the original author of this <.<
/s

**Comment by RWCraft** [comment]
Of what?

**Comment by RWCraft** [comment]
I didn't change it from null@spigotmc.org or whatever when setting up so probably that. Apart from that, it's all my code.

**Comment by Fireflies** [comment]
Just kidding man, /s on the internet is shorthand for sarcasm :stuck_out_tongue:
